
####################################
####### Configure behaviour ########
####################################




####################################
########## Dev settings ############
####################################

# web server flask debug mode and other debug output
debug_mode_flask: False

# debug mode for the rest of the code, more verbose
debug: False

# print time comparisons (encrypted)
print_time_comparison: False

# Debuging outputs, display encrpyted data. 'debug' flag not required
# print data matching query before it is filtered using time (encrypted)
print_pre_time_filtered_data: False
# print data after is it filtered for time (encrypted)
print_time_filtered_data: False
# print response to client (encrpyted)
print_response: False


# return data that matches the query that does not have
# timestamp when doing timestamp queries
# also enables similar behaviour but when timestamp comparison fails
add_missing_data_to_response_on_missing_time: False

####################################
##### no need to change below ######
####################################

# point to db, using db container
backed_DB_uri: "mongodb://priv-backend-db:27017/"

#backend database
db_name: priv_backend
col_name: enc_data


