version: "3.8"
services:

  priv-backend-api:
    # image: priv-backend-api
    container_name: priv-backend-api
    build: .
    restart: always
    ports:
      - "5001:5000"
    networks:
      - priv-backend-net
    environment:
      PYTHONUNBUFFERED: 1

  priv_backend-db:
    container_name: priv-backend-db
    image: "mongo"
    restart: always
    ports:
      - "5003:27017"
    networks:
      - priv-backend-net

    volumes:
      - "./db/db:/data/db"
      - "./db/configdb:/data/configdb"
      - "./db/logs:/var/log/mongodb"

networks:
  priv-backend-net: {}

